# Utilisation de l'image Apache officielle
FROM httpd:latest

# Copier le fichier index.html vers le répertoire /usr/local/apache2/htdocs/ du conteneur
COPY ./html/index.html /usr/local/apache2/htdocs/
